services:
  postgres:
    container_name: postgres_go
    image: postgres
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: todo
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todo"]
      interval: 3s
      timeout: 3s
      retries: 20